### ISSUE TITLE
Sets constant season to summer when used on a realm, seasons never change

### ISSUE THREAD

**Issue by MiloAC1** [slicedlime/seasons#11]

**Comment by slicedlime** [comment]
Realms do not support experimental world generation.

**Comment by MiloAC1** [comment]
Ok that makes sense but now every region of the realm has its season set to summer, which is fine, I understand that a fix is in the works.

**Comment by slicedlime** [comment]
There is no fix. This pack is fundamentally incompatible with Realms until Realms support custom world generation packs.

**Comment by MiloAC1** [comment]
Lovely lol, thank I love the pack
