### ISSUE TITLE
Ping issue

### ISSUE THREAD

**Issue by MichaelGaming12** [slicedlime/seasons#16]
Ever since i have had the datapack, my ping would not stay stable. The weird thing is that if the server starts with datapack on my ping would go sky high, if i install the datapack while playing the ping would be fine. Very weird. Please do tell me if you need more info.

**Comment by MichaelGaming12** [comment]
![image](https://user-images.githubusercontent.com/57291334/226744054-0f00d3c3-8b74-418c-886f-70fc9c8b0f15.png)

**Comment by MichaelGaming12** [comment]
I have also tried disabling it, which lowered my ping to double digits. But upon reenabling it, ping just spikes up.

**Comment by ButterDebugger** [comment]
I'm having the same issue

**Comment by slicedlime** [comment]
This is mentioned in the readme. https://github.com/slicedlime/seasons#performance

**Comment by MichaelGaming12** [comment]
But the TPS is fine so is the MSPT, i dont understand how the ping is related to the data since its just the amount of time it takes the machine to talk to the router.

**Comment by MichaelGaming12** [comment]
And I have very fast wifi, my ping usually is in the double digits.

**Comment by slicedlime** [comment]
> The amount of network data transmitted when using the fillbiome command has been optimized

1.19.4 changelog.

**Comment by slicedlime** [comment]
Literally noted in the readme.
