### ISSUE TITLE
Snow and river ice melts in winter

### ISSUE THREAD

**Issue by kiddailey** [slicedlime/seasons#19]
This has been fun to play around with and watch, Slicedlime - thank you, and I hope you find time and interest in continuing it :)

I started a new world and have set up home in a cliff-side cave in a meadows biome that overlooks a small forest biome and a village in the distance.

When winter started, it snowed and covered all of the surrounding area and the village in snow as expected.  However, shortly thereafter, the snow completely melted away despite being in the middle of the winter season (winter_snowy).  It hasn't snowed for some time, which -- as the snow isn't readily replaced -- is why I think it's so noticeable.

When I watch the rivers, I can see that spots are constantly freezing, melting and re-freezing so they don't become solid ice.  Likewise, I've since discovered that when it snows, snow is melting even as new snow is falling.

Are these expected behaviors?  Or should the snow and ice remain throughout all of winter as I had assumed?

Thanks again!

![SnowAndIceSadness](https://user-images.githubusercontent.com/358292/233705663-9b4916ef-eb56-40b4-9265-8ad3ae7e07b8.jpg)

Ice melting and freezing:

https://user-images.githubusercontent.com/358292/233706894-5e3a93b0-d8be-4b52-9101-ae973683c626.mp4

Snow melting during snowfall:

https://user-images.githubusercontent.com/358292/233714255-af4d754a-c030-43ba-a941-df5326e58901.mp4

Link to world download:

https://mega.nz/file/5ckiUYaQ#v0Uy_N9OR1NLAQNKJ_C4dByo_a0SsmCXCAjk-3D4JTs

**Comment by kiddailey** [comment]
Ha - after I posted that it started to snow and the ground started having snow again.  However, I notice now that as with the river ice, the snow is melting as new snow is falling. Will post a video in a moment.

**Comment by slicedlime** [comment]
Hello - thanks for the report! That is not at all expected - snow and ice are expected to stay through the entire winter. What is the exact biome reported on the F3 screen in that location?

**Comment by kiddailey** [comment]
The current biomes for the loaded areas immediately around me are:

### Mountain/Cave area: 

* seasons:winter_snowy/meadow

### Surrounding areas:

* seasons:winter_snowy/forest
* seasons:winter_snowy/plains

### Rivers:

_Interesting note about the rivers -- if I strafe across them, the seasons change between bare and snowy._

* seasons:winter_bare/river
* seasons:winter_snowy/river

## A few other interesting notes:

* I'm currently on Day 55
* Local Difficulty: 2.70 // 0.35
* I have slept a few times, including during rain/snow, but have also let the precipitation end naturally
* After it snowed again, I've noticed that a bunch of grass blocks have been turned to dirt, while others are still grass with "snowy:true"  It became obvious once the snow started melting and revealed the dirt blocks.   Having lived "up north", mud after snow melts is pretty normal, but not sure this is intended either :)

Let me know if you need anything else.

**Comment by kiddailey** [comment]
I added a link to the world download in the original post if it's helpful.  Spawn point is right near cave, but the cave is around coords 117.325 / 66.963 if you can't find it.

**Comment by slicedlime** [comment]
Should be fixed with beta version 0.3.
