### ISSUE TITLE
Change rate seasons change when going into new terrain

### ISSUE THREAD

**Issue by maloneya26** [slicedlime/seasons#25]
Would there be any way to make it so as soon as I enter the terrain the season changes. I know it might cause a lot of lag but being in a fall biome than randomly walking into summer kind of breaks the immersion

**Comment by slicedlime** [comment]
No, changing the entire terrain really isn't feasible. The pack already makes attempts at skipping quicker to the "correct" season, but having it happen immediately is never going to be an option.
