### ISSUE TITLE
Taiga grass colors are wrong

### ISSUE THREAD

**Issue by slicedlime** [slicedlime/seasons#4]
![image](https://user-images.githubusercontent.com/1653332/221495118-1ca2405a-3bea-451c-bcab-51c3e0a4bd74.jpeg)

Source: https://twitter.com/harptheseal/status/1629912758773792773?s=46&t=pEHOD6689JdFEh3zhOAelw

**Comment by slicedlime** [comment]
More information: The problem is present in all seasons, although with somewhat different (all wrong) colors. Thanks to MintyCheddar on YouTube:

> The purple coloration appears Summer, Fall and Winter, though the purple seems to brighten to magenta in Winter.

**Comment by MintyCheddar** [comment]
The purple discoloration in Taiga biomes can be seen in any season, except 'snowy_winter' when everything turns gray.

**Comment by MintyCheddar** [comment]
Traveled to Taiga biomes away from the spawn point and did not find the purple discoloration in the Taiga, Snowy Taiga, and other biomes there during the Summer season. However, the purple blocks persist in the snowy Groves near the spawn point. I will check the distant Taiga biomes again during Fall.
